import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalPageLayout } from "@/app/components/layout/GlobalPageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalPageLayout>{children}</GlobalPageLayout>
      </body>
    </html>
  );
}
