/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as RecipesRouteImport } from "./routes/recipes/route"
import { Route as StaticRouteImport } from "./routes/_static/route"
import { Route as IndexImport } from "./routes/index"
import { Route as RecipesIndexImport } from "./routes/recipes/index"
import { Route as StaticPrivacyImport } from "./routes/_static/privacy"
import { Route as StaticAboutImport } from "./routes/_static/about"
import { Route as RecipesRecipeIdIndexImport } from "./routes/recipes/$recipeId/index"

// Create/Update Routes

const RecipesRouteRoute = RecipesRouteImport.update({
  path: "/recipes",
  getParentRoute: () => rootRoute,
} as any)

const StaticRouteRoute = StaticRouteImport.update({
  id: "/_static",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  path: "/",
  getParentRoute: () => RecipesRouteRoute,
} as any)

const StaticPrivacyRoute = StaticPrivacyImport.update({
  path: "/privacy",
  getParentRoute: () => StaticRouteRoute,
} as any)

const StaticAboutRoute = StaticAboutImport.update({
  path: "/about",
  getParentRoute: () => StaticRouteRoute,
} as any)

const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexImport.update({
  path: "/$recipeId/",
  getParentRoute: () => RecipesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/_static": {
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRoute
    }
    "/recipes": {
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRoute
    }
    "/_static/about": {
      preLoaderRoute: typeof StaticAboutImport
      parentRoute: typeof StaticRouteImport
    }
    "/_static/privacy": {
      preLoaderRoute: typeof StaticPrivacyImport
      parentRoute: typeof StaticRouteImport
    }
    "/recipes/": {
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof RecipesRouteImport
    }
    "/recipes/$recipeId/": {
      preLoaderRoute: typeof RecipesRecipeIdIndexImport
      parentRoute: typeof RecipesRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  StaticRouteRoute.addChildren([StaticAboutRoute, StaticPrivacyRoute]),
  RecipesRouteRoute.addChildren([RecipesIndexRoute, RecipesRecipeIdIndexRoute]),
])

/* prettier-ignore-end */
