/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as IndexImport } from "./pages/index"
import { Route as RecipesIndexImport } from "./pages/recipes/index"
import { Route as RecipesRecipeIdIndexImport } from "./pages/recipes/$recipeId/index"
import { Route as RecipesRecipeIdShoppinglistImport } from "./pages/recipes/$recipeId/shoppinglist"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  path: "/recipes/",
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexImport.update({
  path: "/recipes/$recipeId/",
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdShoppinglistRoute =
  RecipesRecipeIdShoppinglistImport.update({
    path: "/recipes/$recipeId/shoppinglist",
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/recipes/": {
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
    "/recipes/$recipeId/shoppinglist": {
      preLoaderRoute: typeof RecipesRecipeIdShoppinglistImport
      parentRoute: typeof rootRoute
    }
    "/recipes/$recipeId/": {
      preLoaderRoute: typeof RecipesRecipeIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  RecipesIndexRoute,
  RecipesRecipeIdShoppinglistRoute,
  RecipesRecipeIdIndexRoute,
])

/* prettier-ignore-end */
