/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as RecipesImport } from "./pages/recipes"
import { Route as PrivacyImport } from "./pages/privacy"
import { Route as AboutImport } from "./pages/about"
import { Route as IndexImport } from "./pages/index"
import { Route as RecipesIndexImport } from "./pages/recipes/index"
import { Route as RecipesRecipeIdIndexImport } from "./pages/recipes/$recipeId/index"
import { Route as RecipesRecipeIdShoppinglistImport } from "./pages/recipes/$recipeId/shoppinglist"

// Create/Update Routes

const RecipesRoute = RecipesImport.update({
  path: "/recipes",
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  path: "/privacy",
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  path: "/",
  getParentRoute: () => RecipesRoute,
} as any)

const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexImport.update({
  path: "/$recipeId/",
  getParentRoute: () => RecipesRoute,
} as any)

const RecipesRecipeIdShoppinglistRoute =
  RecipesRecipeIdShoppinglistImport.update({
    path: "/$recipeId/shoppinglist",
    getParentRoute: () => RecipesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/about": {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    "/privacy": {
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    "/recipes": {
      preLoaderRoute: typeof RecipesImport
      parentRoute: typeof rootRoute
    }
    "/recipes/": {
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof RecipesImport
    }
    "/recipes/$recipeId/shoppinglist": {
      preLoaderRoute: typeof RecipesRecipeIdShoppinglistImport
      parentRoute: typeof RecipesImport
    }
    "/recipes/$recipeId/": {
      preLoaderRoute: typeof RecipesRecipeIdIndexImport
      parentRoute: typeof RecipesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  PrivacyRoute,
  RecipesRoute.addChildren([
    RecipesIndexRoute,
    RecipesRecipeIdShoppinglistRoute,
    RecipesRecipeIdIndexRoute,
  ]),
])

/* prettier-ignore-end */
